<?php 
$_aClassFiles = array( 
	"TextTruncator_AdminPage"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/TextTruncator_AdminPage.php", 
	"TextTruncator_AdminPage_Setting"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/setting/TextTruncator_AdminPage_Setting.php", 
	"TextTruncator_AdminPage_Setting_General"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/setting/general/TextTruncator_AdminPage_Setting_General.php", 
	"TextTruncator_AdminPage_Setting_General_Reset"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/setting/general/TextTruncator_AdminPage_Setting_General_Reset.php", 
	"TextTruncator_AdminPage_Setting_Truncator"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/setting/truncator/TextTruncator_AdminPage_Setting_Truncator.php", 
	"TextTruncator_AdminPage_Setting_Truncator_Definition"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/setting/truncator/TextTruncator_AdminPage_Setting_Truncator_Definition.php", 
	"TextTruncator_AdminPage_Page_Base"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/_abstract/TextTruncator_AdminPage_Page_Base.php", 
	"TextTruncator_AdminPage_RootBase"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/_abstract/TextTruncator_AdminPage_RootBase.php", 
	"TextTruncator_AdminPage_Section_Base"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/_abstract/TextTruncator_AdminPage_Section_Base.php", 
	"TextTruncator_AdminPage_Tab_Base"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/_abstract/TextTruncator_AdminPage_Tab_Base.php", 
	"TextTruncator_AdminPage_Tab_ReadMeBase"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/_abstract/TextTruncator_AdminPage_Tab_ReadMeBase.php", 
	"TextTruncator_SimpleWizardAdminPage"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/_abstract/TextTruncator_SimpleWizardAdminPage.php", 
	"TextTruncator_FormFields_Base"	=>	TextTruncator_Registry::$sDirPath . "/include/class/admin/_form_fields/TextTruncator_FormFields_Base.php", 
	"TextTruncator_Bootstrap"	=>	TextTruncator_Registry::$sDirPath . "/include/class/boot/TextTruncator_Bootstrap.php", 
	"TextTruncator_Option"	=>	TextTruncator_Registry::$sDirPath . "/include/class/option/TextTruncator_Option.php", 
	"TextTruncator_Option_Base"	=>	TextTruncator_Registry::$sDirPath . "/include/class/option/TextTruncator_Option_Base.php", 
	"TextTruncator_ScriptLoader"	=>	TextTruncator_Registry::$sDirPath . "/include/class/script/TextTruncator_ScriptLoader.php", 
	"TextTruncator_Debug"	=>	TextTruncator_Registry::$sDirPath . "/include/class/utility/TextTruncator_Debug.php", 
	"TextTruncator_PluginUtility"	=>	TextTruncator_Registry::$sDirPath . "/include/class/utility/TextTruncator_PluginUtility.php", 
	"TextTruncator_Utility"	=>	TextTruncator_Registry::$sDirPath . "/include/class/utility/TextTruncator_Utility.php", 
	"TextTruncator_WPUtility"	=>	TextTruncator_Registry::$sDirPath . "/include/class/utility/TextTruncator_WPUtility.php", 
	"TextTruncator_WPUtility_Transient"	=>	TextTruncator_Registry::$sDirPath . "/include/class/utility/TextTruncator_WPUtility_Transient.php", 
);